"""Orbital mechanics and the coast phase (Paper II, §7)."""

from __future__ import annotations

from passes.orbital.coast import (
    CoastResult,
    RegimeTransition,
    StrategyComparison,
    compare_coast_strategies,
    orbital_elements,
    propagate_coast,
    regime_transition_profile,
    secular_rates,
)
from passes.orbital.fobs import (
    EARTH_ROTATION_RATE,
    DeorbitBurn,
    FobsProfile,
    FractionalInsertion,
    approach_azimuth,
    azimuth_envelope,
    deorbit_burn,
    fobs_profile,
    fractional_insertion,
    ground_track,
    ground_track_shift,
)
from passes.orbital.gravity import (
    EARTH,
    GravityModel,
    gravitational_acceleration,
    gravitational_potential,
    j2_acceleration,
    specific_angular_momentum_z,
    specific_energy,
    two_body_acceleration,
)
from passes.orbital.lambert import (
    LambertSolution,
    lambert,
    minimum_energy_transfer,
)
from passes.orbital.radar import (
    EARLY_WARNING_SITES,
    SATELLITE_SENSORS,
    CoverageResult,
    RadarSite,
    SatelliteSensor,
    SensorCapability,
    coverage,
    site,
)
from passes.orbital.warning import (
    DetectionWindow,
    detection_window,
    horizon_central_angle,
    visibility_radius,
)

__all__ = [
    "EARLY_WARNING_SITES",
    "EARTH",
    "EARTH_ROTATION_RATE",
    "SATELLITE_SENSORS",
    "CoastResult",
    "CoverageResult",
    "DeorbitBurn",
    "DetectionWindow",
    "FobsProfile",
    "FractionalInsertion",
    "GravityModel",
    "LambertSolution",
    "RadarSite",
    "RegimeTransition",
    "SatelliteSensor",
    "SensorCapability",
    "StrategyComparison",
    "approach_azimuth",
    "azimuth_envelope",
    "compare_coast_strategies",
    "coverage",
    "deorbit_burn",
    "detection_window",
    "fobs_profile",
    "fractional_insertion",
    "gravitational_acceleration",
    "gravitational_potential",
    "ground_track",
    "ground_track_shift",
    "horizon_central_angle",
    "j2_acceleration",
    "lambert",
    "minimum_energy_transfer",
    "orbital_elements",
    "propagate_coast",
    "regime_transition_profile",
    "secular_rates",
    "site",
    "specific_angular_momentum_z",
    "specific_energy",
    "two_body_acceleration",
    "visibility_radius",
]
